### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by stel-bl** [d-go/quick-settings-avatar#11]
GNOME 46 got released and the extension is reported incompatible. Bumping Shell version support to 46 in `metadata.json` gets it up and running for the most part, but clicking on the profile picture doesn't open user settings in that case.

I created [a fork that bumps the version](https://github.com/stel-bl/quick-settings-avatar) for those who still want to use it without waiting for an actual update. Just zip the code and install it using `gnome-extensions install quick-settings-avatar.zip`.

**Comment by azomDev** [comment]
I found that just going into `~/.local/share/gnome-shell/extensions/quick-settings-avatar@d-go/metadata.json`, changing this line:
`"shell-version": ["45"],`
to this line:
`"shell-version": ["46"],`
also works without network access and might be easier in some cases :P

**Comment by stel-bl** [comment]
I mean yeah, that also works. I personally prefer doing it that way just in case...you know what I mean?

**Comment by d-go** [comment]
Support for Gnome 46  is on its way, it fixes the issue when clicking on the avatar profile (caused by the change in the new "System" panel in settings, the path to the Users settings changed as well)
