### ISSUE TITLE
Quick settings seem glitch in random situation

### ISSUE THREAD

**Issue by Anifyuli** [d-go/quick-settings-avatar#4]
Hello, Mister.
I want to report little problem in your GNOME extension. I found glitch in random situation on quick settings menus. In this attached screenshot you can inspect this problem. 
![Screenshot from 2022-12-02 07-22-45](https://user-images.githubusercontent.com/73734843/207603080-61557784-906b-4537-91ea-2e67f216edf9.png)
I think it's GNOME shell bugs. But after report to GNOME shell issue, someone reply my submitted issue because a extension make quick settings expanded from previous state. You can read my issue in [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6210) or in [my other submitted issue](https://github.com/stuarthayhurst/privacy-menu-extension/issues/20). In this day I try to disable your extension and this glitch not appear again in several times and I'm not sure if your extension caused this problem. 
I wish you not angry or offended because my opinion. Thanks for read my issue. Sorry my English

**Comment by d-go** [comment]
Hi!, thanks for reporting the issue.
I'm able to reproduce this bug, although it is reproducible to me when the size value is multiple of 2 (even) e.g. 46, 48, 50, etc.
I think this is definitely not an issue with the extension itself but the extension makes this bug to appear or more obvious, what I can do is to round the configured value to not be even, not the best approach I think, but this will prevent this issue to appear.

**Comment by Anifyuli** [comment]
Thanks for your reply, Mister

**Comment by d-go** [comment]
@Anifyuli just submitted the new version (hopefully with this issue fixed) in [gnome-shell](https://extensions.gnome.org/extension/5506/user-avatar-in-quick-settings/), will be released in some hours probably. 
Please let me know if you see this issue fixed on your end once you get the new version installed.

**Comment by Anifyuli** [comment]
Updates from you can solve this problem, but I see rare condition this issue appear in fewer chances. First time re-activate your extension after latest update this issue appear, but after I open extension settings and try to enable or disable a feature from your extension, glitch can disappear. In this screenshot bug appear again with latest update too
![image](https://user-images.githubusercontent.com/73734843/208690791-d2175de9-84d3-4cc7-b469-d6bdc19d6e24.png)

**Comment by d-go** [comment]
> Updates from you can solve this problem, but I see rare condition this issue appear in fewer chances. First time re-activate your extension after latest update this issue appear, but after I open extension settings and try to enable or disable a feature from your extension, glitch can disappear. In this screenshot bug appear again with latest update too.
> 
> Edit : after change icon size to 36 this issue not appear and I check with `Main.panel.statusArea['quickSettings'].menu.box.width` in lightglass is in standard size (value is 402)
> 
> ![image](https://user-images.githubusercontent.com/73734843/208690791-d2175de9-84d3-4cc7-b469-d6bdc19d6e24.png)

In the screenshot I still see this issue, did you try to log out and log in again after the update? gnome-shell makes a fresh load of  plugins on log in. 
Let me know if this is reproducible so I re-open the issue, otherwise we can consider it as fixed.

**Comment by Anifyuli** [comment]
I activate your extension in latest version after rebooting system because after installing kernel updates, so my active session (in my screenshot) is refreshed
