### ISSUE TITLE
Add support for GNOME 44

### ISSUE THREAD

**Issue by Scotty-Trees** [d-go/quick-settings-avatar#6]
Greetings,

I know it's still a little bit early, but Gnome 44 alpha/beta are out now for testing purposes and I was wondering if/when the extension will be updated? Some extensions are already being updated to support the latest which is very nice to see. The final release for Gnome 44 should be on March 22nd, 2023 btw. Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

**Comment by d-go** [comment]
Hey :wave:, thanks for reaching out! 
Definitely will take a look and I'll try to test it in Gnome 44 in the upcoming days, appreciate your comments and patience.
Regards.

**Comment by Scotty-Trees** [comment]
No worries, looking forward to seeing this extension continued developments :+1:

**Comment by Scotty-Trees** [comment]
Happy to see! Looking forward to updating to Fedora 38 next month. Thanks again for your work, love your extension very much :)
