### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yukina3230** [d-go/quick-settings-avatar#8]
Hi @d-go , thank you for making this awesome extension, GNOME 45 will be released on September 20th, hope to see it has support for the new version, may need some changes because of the new ESM standard.

This link might help: [https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm)

**Comment by d-go** [comment]
Thanks, @yukina3230!, I'll definitely take a look at it, and hopefully will get the upgraded version in this month. Appreciate your comments and patience.
